In [2]:
import numpy as np



In [28]:
string = ' 0  0  1   0.0'
def parse_constraint(string):
    # print(list(filter(lambda x: x!='', string.split(' '))))
    x, y, z, c = [float(i) for i in string.split(' ') if i != '']
    return np.array([x, y, z]), c

parse_constraint(string)

string = 'xyZ  0 0 0  1'
string = 'ZYX  1 1 1  2'
def parse_symmetry(string):
    items = [i for i in string.split(' ') if i != '']
    scheme = items[0]
    x, y, z, c = list(map(float, items[1:]))

    mat_temp = []
    for cc in scheme:
        cu = cc.upper()
        if cu == 'X':
            mat_temp.append([1, 0, 0] if cc == 'x' else [-1, 0, 0])
        elif cu == 'Y':
            mat_temp.append([0, 1, 0] if cc == 'y' else [0, -1, 0])
        elif cu == 'Z':
            mat_temp.append([0, 0, 1] if cc == 'z' else [0, 0, -1])

    return np.array(mat_temp).T, np.array([x, y, z]) / c
    

parse_symmetry(string)

string = 'l  24  3  0 0 0  1   1 0 0  0 1 0  0 0 1'
string = 'k  12  2  1 0 0  2   0 1 0  0 0 1'
string = 'i   8  1  0 0 0  1   1 1 1'
string = 'd   3  0  0 1 0  2'

def parse_wyckoff_position(string):
    items = [i for i in string.split(' ') if i != '']
    pos_name = items[0]
    n_atoms = int(items[1])
    n_degree_of_freedom = int(items[2])

    x, y, z, c, *vecs_info = list(map(float, items[3:]))

    vecs = []
    for i in range(n_degree_of_freedom):
        vx, vy, vz = vecs_info[i*3:(i+1)*3]
        vecs.append(np.array([vx, vy, vz]))

    return pos_name, n_atoms, n_degree_of_freedom, np.array([x, y, z]) / c, vecs


parse_wyckoff_position(string)

def load_data(group_type):
    constraints = []
    reverse_symmetry = []
    symmetry = []
    wyckoff_positions = {}
    with open('CUBIC.DAT') as file:
        while (line := file.readline().strip()) != group_type:
            print(line)
            if line == 'HALT':
                return

        print("HERE!!!!!!!!!!!!!!")

        n = int(file.readline())
        for _ in range(n):
            constraints.append(parse_constraint(file.readline().strip()))
        for _ in range(n):
            reverse_symmetry.append(parse_symmetry(file.readline().strip()))

        n = int(file.readline())
        for _ in range(n):
            symmetry.append(parse_symmetry(file.readline().strip()))

        n = int(file.readline())
        for _ in range(n):
            temp = parse_wyckoff_position(file.readline().strip())
            wyckoff_positions[temp[0]] = temp[1:]

    return constraints, reverse_symmetry, symmetry, wyckoff_positions

load_data('Fd3m')

P23
4
0  0  1   0.0
-1 -1  0  -1.0
1  0 -1   0.0
0  1 -1   0.0
XyZ  1 0 0  1
XYz  1 1 0  1
yzx  0 0 0  1
zxy  0 0 0  1
20
XyZ  1 0 0  1
xYZ  0 1 0  1
XYz  1 1 0  1
yzx  0 0 0  1
zxy  0 0 0  1
XYz  1 0 0  1
XYz  0 1 0  1
XYz  0 0 0  1
XYz  2 0 0  1
XYz  0 2 0  1
YzX  1 0 0  1
ZxY  1 0 0  1
yZX  0 1 0  1
zXY  0 1 0  1
YZx  1 1 0  1
ZXy  1 1 0  1
xYZ  0 0 0  1
XyZ  0 0 0  1
xYZ  0 2 0  1
XyZ  2 0 0  1
10
j  12  3  0 0 0  1   1 0 0  0 1 0  0 0 1
i   6  1  0 1 1  2   1 0 0
h   6  1  0 1 0  2   1 0 0
g   6  1  0 0 1  2   1 0 0
f   6  1  0 0 0  1   0 1 0
e   4  1  0 0 0  1   1 1 1
d   3  0  0 1 0  2
c   3  0  1 1 0  2
b   1  0  1 1 1  2
a   1  0  0 0 0  1
F23
5
1 -1  0   0.0
-1  0  1  -0.5
0  1  1   0.0
-1  0 -1  -0.5
0  1 -1   0.0
XYz  1 1 0  2
YZx  1 0 -1  2
zXY  1 1 0  2
YzX  1 0 1  2
ZXy  1 1 0  2
16
XYz  1 1 0  2
zXY  1 1 0  2
YZx  1 0 -1  2
ZXy  1 1 0  2
YzX  1 0 1  2
XYz  0 0 0  1
XYz  1 1 0  1
XYz  1 0 0  1
xYZ  0 0 0  1
XyZ  1 0 0  1
yzx  0 0 0  1
yZX  0 0 0  1
ZxY  1 0 1  2
zxy  1 0

([(array([0., 1., 1.]), 0.0),
  (array([ 0.,  1., -1.]), 0.0),
  (array([ 1., -1.,  0.]), 0.0),
  (array([-1., -1.,  0.]), -0.5),
  (array([ 0., -1.,  0.]), -0.125)],
 [(array([[ 1,  0,  0],
          [ 0,  0, -1],
          [ 0, -1,  0]]),
   array([0., 0., 0.])),
  (array([[1, 0, 0],
          [0, 0, 1],
          [0, 1, 0]]),
   array([0., 0., 0.])),
  (array([[0, 1, 0],
          [1, 0, 0],
          [0, 0, 1]]),
   array([0., 0., 0.])),
  (array([[ 0, -1,  0],
          [-1,  0,  0],
          [ 0,  0,  1]]),
   array([0.5, 0.5, 0. ])),
  (array([[ 0,  0, -1],
          [ 0, -1,  0],
          [-1,  0,  0]]),
   array([0.25, 0.25, 0.25]))],
 [(array([[ 1,  0,  0],
          [ 0,  0, -1],
          [ 0, -1,  0]]),
   array([0., 0., 0.])),
  (array([[1, 0, 0],
          [0, 0, 1],
          [0, 1, 0]]),
   array([0., 0., 0.])),
  (array([[0, 1, 0],
          [1, 0, 0],
          [0, 0, 1]]),
   array([0., 0., 0.])),
  (array([[ 0, -1,  0],
          [-1,  0,  0],
          [ 0,  0, 

In [ ]:
group_type = 'Fd3m'
